#!/bin/sh

export NATS_HOME=${PWD}

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NATS_HOME/dist

#sh $NATS_HOME/utility/run_nodejs.sh &

TARGET_PS=$(lsof -i tcp:2020 | awk 'NR!=1 {print $2}')

if [ "${TARGET_PS}" != '' ] ;   then
   set echo off
   
   kill -15 $TARGET_PS > /dev/null
   
   set echo on
fi

TARGET_PS=$(/usr/bin/jps | grep 'NATSStandaloneServer' | awk '{print $1}')

if [ "${TARGET_PS}" != '' ] ;   then
   set echo off
   
   kill -15 $TARGET_PS > /dev/null
   
   set echo on
fi

sleep 1

/usr/bin/java -cp $NATS_HOME/dist/nats-standalone.jar:$NATS_HOME/dist/nats-server.jar:$NATS_HOME/dist/nats-shared.jar:$NATS_HOME/dist/commons-logging-1.2.jar -Djava.library.path=$NATS_HOME/dist -Xmx768m NATSStandaloneServer
